### ISSUE TITLE
Add git actions to branch page

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/droid#12]
DROID has one git working copy per branch. Authorized users should see a "Version Control" section (below the "Workflow" section) with helpful text and buttons to run various `git` tasks. Clicking a button will run the `git` command-line client and log results to the console.

- Status: `git status` Show which files have changed since the last commit
- Diff: `git diff` Show changes to tracked files since the last commit
- Fetch: `git fetch` Fetch the latest changes from GitHub
- Pull: `git pull` Update this branch with the lastest changes from GitHub
- Commit: `git commit --all` Commit your changes [and ask for a commit message]
- Amend: `git commit --all --amend` Update you last commit with new changes
- Push: `git push` Push your changes to GitHub [and maybe use the GtiHub API to immediately create a PR]

(I think we should not distinguish git staging for this purpose, which is why I prefer `git commit --all` without a separate `git add` button.)

I think that if the git working copy is checked out using HTTPS then the OAuth token that DROID already has can be used to authorized `git` operations. But I'm not 100% sure. There are some alternatives.

**Comment by jamesaoverton** [comment]
Only authorized users (as discussed in #22) should see these git action buttons and be allowed to run these actions.

**Comment by lmcmicu** [comment]
If possible, the git output should be colourized, i.e. the server should be able to read the ANSI colour codes in git's output and convert those to HTML before rendering it. There are libraries for this, for example there is a python library called `ansi2html`: https://pypi.org/project/ansi2html/. The server could run a script on the command line to call that library and then render its html output.
