### ISSUE TITLE
Optionally execute branch tasks in Docker

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/droid#13]
I'm not a fan of Docker, but there's a number of advantages to having DROID execute tasks such as `make foo` inside Docker:

1. isolate project dependencies from DROID dependencies
2. cleaner execution environment
3. generally safer, although not completely safe
4. offload computations to containers on other machines

Note that these are quite different goals, but the implementation might overlap.

Steps:

1. make this work with local Docker, with something like `docker run --env ... --mount ... IMAGE "make ..."` (suggestions welcome)
2. configure the Docker image in each `droid.yml`
3. consider allowing each branch/workspace to define a Dockerfile
4. explore the option of pushing execution to somebody else's container service

**Comment by jamesaoverton** [comment]
I've figured out how to make this work with NixOS containers, as opposed to Docker containers. Pragmatism still favours Docker, since everybody's doing it.

**Comment by jamesaoverton** [comment]
Consider: https://aws.amazon.com/fargate/

**Comment by jamesaoverton** [comment]
Consider that this might not need to be part of DROID at all, just that DROID might be aware of it and pass the right configs in the environment.

Before we build anything, we should look for an existing tool. This is a good candidate: https://github.com/awslabs/fargatecli

**Comment by lmcmicu** [comment]
Local docker should be working now. We will split off the remote part into a new issue: https://github.com/ontodev/droid/issues/40
