### ISSUE TITLE
Try hiccup2 and raw-string for console

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/droid#34]
In 1b1e1bc59ff71766cf70c7878d71266c9392f1ee I added a hack that limits the size of the console that we pass through `ansi2html`. The problem isn't `ansi2html`, but passing large HTML strings through `hiccup` could lock up the server.

The 2.0 series of `hiccup` (still in alpha) has a `hiccup.util/raw-string` function that might solve this problem. I'm not sure if moving to 2.0 changes the APIs we care about.

So let's try `hiccup` 2.0 and allows us to pass a few MB of HTML through `ansi2html` and into the rendered page.

**Comment by lmcmicu** [comment]
closed by https://github.com/ontodev/droid/commit/b5d74c3ed50d2674a15a03288a1370a682d64755
