### ISSUE TITLE
Removing python dependency

### ISSUE THREAD

**Issue by bjonnh** [ontodev/droid#39]
As Python is only used for ansi2html, wouldn't it be wise to use a Java library to do the Ansi2HTML?

There is that one:
https://github.com/fusesource/jansi

that seem to have an HTML output for its ANSI streams (I didn't test it yet)

**Comment by jamesaoverton** [comment]
It's a good suggestion. We've been using Python for the various projects hosted by DROID, so this hasn't been inconvenient so far, but we'll see where we are once #13 is done.

**Comment by lmcmicu** [comment]
I hadn't heard of `jansi`. We tried https://github.com/lambdaisland/ansi but it was significantly slower than `ansi2html` (~10s vs ~2s on one test)

Having fewer moving parts is a good thing all else equal, so it's worth having a look to see what the performance is like with `jansi`.
