### ISSUE TITLE
Optionally execute branch tasks in remote Docker

### ISSUE THREAD

**Issue by lmcmicu** [ontodev/droid#40]
This was originally part of issue https://github.com/ontodev/droid/issues/13. We have split that one into two. The original issue will be for local docker, this is for remote docker, i.e., pushing containers to the cloud so that they can run there.

We are leaning toward Amazon ECS/Fargate as the preferred solution. See https://aws.amazon.com/fargate/ and this tool: https://github.com/awslabs/fargatecli

**Comment by jamesaoverton** [comment]
@lmcmicu looked into the details of this, and it seems to be more complicated than I had hoped. We'll set this aside for now.

**Comment by jamesaoverton** [comment]
We have no plans to implement this, so I'll close this issue.
