### ISSUE TITLE
Quick dump of feature requests (nothing urgent, just so I dont forget)

### ISSUE THREAD

**Issue by matentzn** [ontodev/droid#42]
- [ ] git reset -hard button
- [ ] some way to add untracked files (maybe just expose a git console?)
- [ ] Some way to docker pull a new version of the ODK?

**Comment by jamesaoverton** [comment]
I agree with the first one and created issue #43.

I'm trying not to make DROID into a full editor, but it's awfully tempting. A few options (limited to admins only):

1. some easy-ish way to SSH/SFTP into the container
2. [added] a simple input box for executing commands in the container
3. add an (existing, open source) web-based terminal to DROID
4. connect to somebody else's Web IDE

Right now Docker images are pulled on server startup. We can think about exposing more control.

**Comment by jamesaoverton** [comment]
- [X] git reset -hard button -- closed by #43
- [X] some way to add untracked files (maybe just expose a git console?) -- I don't want to add a button for this, but we can now do it via Make or CGI script, so I'll count this as closed
- [X] Some way to docker pull a new version of the ODK? -- DROID should now read the `Dockerfile` in the root of a branch and use it, so I think that covers this.
