### ISSUE TITLE
Add git reset --hard button

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/droid#43]
O agree with the first request in #42 that we should add a button that can reset changes to the branch.

The problem is that there's more than one reasonable behaviour. My current preference is `git reset --hard`, which I often use to clean a branch so I can pull. But there may be better ideas.

- use a red "Reset" button: "Reset this branch to the last commit"
- I think it make sense to place it after "pull" (at the bottom)
- since this is destructive, there should be a confirmation: "Reset will delete all changes since the last commit. This cannot be undone. Are you sure?": "Cancel" "Reset branch"

If we decide that there's more than one behaviour that we want to support, maybe the confirmation step can offer more options.

**Comment by matentzn** [comment]
This is great! I like it.
