### ISSUE TITLE
Tighter integration with ODK

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/droid#46]
By design, DROID doesn't know anything about ontologies. But our main use cases are running ontology build systems, more specifically for OBO projects, many of which use [ODK](https://github.com/INCATools/ontology-development-kit).

DROID can now be configured with a Docker image for a given project. When a branch is checked out for that project, DROID creates a Docker container for that branch, and runs all tasks inside it. This fork of ZECO demonstrates that:

https://droid.ontodev.com/ZECO/branches/master

But we need to do a bit more work. DROID looks for a `Makefile` at the top-level of the branch, reads a special "Workflow" comment block from it, and displays that using a few tricks. Then the user clicks on various links/buttons to run tasks and view files.

ODK uses `Makefile`s but they're in `src/ontology/Makefile` and `src/ontology/foo.Makefile`. For the ZECO fork we've added a top-level `Makefile` with a Workflow block. Here's what that looks like (the version you see on DROID might be modified from the version on GitHub): https://github.com/jamesaoverton/zebrafish-experimental-conditions-ontology/blob/master/Makefile#L1

What's the best way to allow ODK projects to be used from DROID? Ideally it would work out-of-the-box, but I expect that some variation will have to be supported. Some ideas:

1. DROID configuration override to specify a different `Makefile`
2. DROID searches the branch for `Makefile`s to use -- I think this could cause problems
3. DROID uses some other source for the Workflow block, maybe the README?

I like (1) best. Could we expect each ODK using DROID to add a Workflow block to their `src/ontology/foo.Makefile`, then tell DROID to use that? @matentzn @cmungall

**Comment by matentzn** [comment]
- I like 1. 
- I dont like 2.
- I dont mind so much about 3, but I dont like the README.md plan :D 
Naturally, I would like the project.yaml file for that. But to be honest, if we just do 1, then I can add the workflow blocks into the src/ontology/Makefile in whatever way we want; so my vote goes clearly for just 1, and thats that. 

The only complication is this taht src/ontology/Makefile is the primary makefile, that imports zeco.Makefile. So DROID needs to be smart enough to point to Makefile, and get the workflow from zeco.Makefile. If that is too difficult, we could add the config to project.yml, or even `droid.yml` (I would not mind that at all - since we may want to add configuration options in the future).

**Comment by jamesaoverton** [comment]
Ok. We should keep working toward a `project.yaml` for our ontology work. But I'm trying hard to make DROID as agnostic as possible about the projects that it's running, so I don't want DROID to care about any `project.yml`.

I'd also like to avoid a `droid.yml`. Right now there's just one `config.edn` for the whole DROID server.

Pointing to two `Makefile`s is kind of annoying, but possible. Maybe we could point DROID to the `src/ontology/Makefile` then make it smart enough to follow the `include foo.Makefile` statement, and find the Workflow block there. The simple case of following a single import is fine, but it looks like lots of complexity is supported by Make:

https://www.gnu.org/software/make/manual/html_node/Include.html

I would only want to support the simple case.

**Comment by matentzn** [comment]
There is I think another problem with 1.

The ODK Makefile is broken in 2:
1. The ODK managed one (`src/ontology/Makefile`)
2. The custom one (`src/ontology/myont.Makefile`). Makefile has an `include` statement to include `myont.Makefile`.

This begs the question of where droid should look for workflows: the static Makefile, or the customisable part. I assume it is out of the question to make it possible for Droid to read the makefile and follow the includes as well, so we can split fixed general workflows from custom ones as well? I would love that, but not sure how hard it would be to achieve this...

**Comment by matentzn** [comment]
Oh I had already mentioned that above.. Today is not my read first day,.

**Comment by jamesaoverton** [comment]
I think this issue is sufficiently covered by #85, which has been implemented.
