### ISSUE TITLE
Implement "local" mode

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/droid#51]
Sometimes it's convenient to run DROID locally. Right now technical people can do this with a bit of work, but it would be good to make it easier for non-technical people.

The main thing is just to run a single JAR file, but there's a few complications:

1. DROID currently expects a Python environment #39 but we can eliminate this
2. DROID wants to authenticate users with GitHub OAuth

The current solution to 2 is to create an OAuth App pointing to localhost, and provide the Client ID and Client Secret to DROID. With some changes we could make DROID accept a single user's Personal Access Token. Since we need to talk to GitHub API, I don't see how we can eliminate this, but we want to make it as easy as possible.

@matentzn suggested that more control over the working directories would also be good. Keep in mind that DROID is designed around a correspondence between: one branch, one working directory, one Docker container (optional), and one working process. Users can mess around in the working directory, running commands and editing files and doing pretty much anything, even `git pull` and `git push`, but one thing they must not do is change the git branch (`git checkout some_other_branch`), or DROID will be very confused.

@matentzn also suggested Dockerizing DROID. The main problem I see with that is controlling other Docker containers from within a Docker container: that used to be difficult or impossible, but maybe things have changed. But Docker containers are optional for DROID, so running DROID inside Docker should be fine if DROID is not also trying to run its own Docker containers.

**Comment by matentzn** [comment]
Just a braindump now:

1. I finished my edits using Protege
2. I open Droid locally
3. I create a new branch based on the current one (uncommited changes follow along)
4. I do housekeeping: QC, building stuff, refreshing imports.
5. I commit/push/make pull request


Lets think about this a bit more in the next months we develop anything.. The much more interesting thing for me would be a button for running a github release, but even that; I think I want to get some more experience with DROID for now.

**Comment by jamesaoverton** [comment]
If we switch the order a bit then we don't have to change DROID much:

1. Start DROID locally (maybe in Docker, assume already configured)
2. Use DROID to create a new branch (which creates a new local working directory)
3. Edit working directory files in Protege or Excel or whatever
4. Run build tasks from DROID (instead of the command-line)
5. Run version control tasks from DROID (instead of the command-line)

You're right that this isn't a rush, and more experience would be good before making major changes.

**Comment by lmcmicu** [comment]
Thanks for the feedback, @matentzn . If we end up deciding in favour of this, I think it should be relatively straightforward to add another button to the version control section of the the interface to create a release tag, which could then be pushed using the `push` button. The current buttons are essentially wrappers around a number of common command line invocations of `git`. Adding another one should not be very much trouble.

Otherwise I echo everything @jamesaoverton said. The main thing we need to stick to (or else significantly change the current design) is the branch->filesystem directory mapping.

**Comment by lmcmicu** [comment]
Regarding `droid` being confused otherwise, it just occurred to me that it might be desirable for `droid` to check that this mapping has actually been preserved and issue some sort of warning if it is not. I can imagine a user running tasks using a mix of droid and direct command line invocations, and forgetting the rule about changing branches within one of droid's workspace directories. `droid` should probably tell the user if it suspects that this has occurred and possibly force the user to fix it before doing anything further.

**Comment by jamesaoverton** [comment]
@lmcmicu You're right. That check is cheap, so it makes sense to just implement it, regardless of this issue.

**Comment by jamesaoverton** [comment]
For this to work well, it would be good to resolve #39

**Comment by lmcmicu** [comment]
One thing we need to be aware of when implementing this is that, when droid is run in local mode as a non-root user there may be filesystem permission issues that arise for shared folders. See: https://vsupalov.com/docker-shared-permissions/ for some hints on how to resolve this.

**Comment by lmcmicu** [comment]
FYI #39 is resolved pending approval.

**Comment by lmcmicu** [comment]
As @jamesaoverton mentioned, running DROID in docker should be fine as long as DROID is not also trying to run its own Docker containers. What this means, concretely, is that in the configuration file `config.edn`, the `:active?` parameter must be set to `false` for every docker configuration. E.g.,

```
{:projects
 {"for-testing-with-droid" {:project-title "4TESTWDROID"
                            :project-welcome "Welcome to 4TESTWDROID!"
                            :project-description "This project is set up to test DROID development"
                            :github-coordinates "lmcmicu/for-testing-with-droid"
                            :env {"TEST" "testy"
                                  "FEST" "festy"}
                            :docker-config {:active? false
                                            :image "debian"
                                            :workspace-dir "/workspace/"
                                            :temp-dir "/tmp/droid/"
                                            :shell-command "sh"
                                            :default-working-dir "/workspace/"
...
```

Note that **each project has its own** `:docker-config` block so you must **disable all of them.**

As for running DROID in a docker container and allowing DROID to run its own containers, this is not impossible but it is tricky and full of gotchas. It is recommended to do so only if your use case really really requires it. See this excellent blog post for info on how to do this correctly: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by lmcmicu** [comment]
Further to my comment (https://github.com/ontodev/droid/issues/51#issuecomment-735746724): I've tried the first use case (running DROID in a docker container, assuming DROID won't be launching its own containers) and it works. You need to install `java` and if you want to colourise the console you will need to also install `aha`. The following Dockerfile should work, for example:
```
FROM debian:buster
RUN apt-get update && apt-get -y install openjdk-11-jdk aha
```

When you create your container you will need it to be able to see the jar file. E.g.,

`docker create --interactive --tty --name docker-for-droid --volume /home/mike/Knocean/droid/target/uberjar/:/tmp docker-for-droid sh`

And you will need to define the environment variables for the GitHub App etc. as well (see DROID's README)

**Comment by matentzn** [comment]
This is great @lmcmicu thanks for looking into that! I will try it as well!

**Comment by lmcmicu** [comment]
No worries @matentzn . Note that besides java and aha you will also need to install in your docker image whatever programs are required to run your CGI scripts (python etc.)

**Comment by matentzn** [comment]
In any case, I will actually try to embed it into an existing container (ODK) which is already widely used. I will let you know how it goes!
