### ISSUE TITLE
UI feedback

### ISSUE THREAD

**Issue by matentzn** [ontodev/droid#52]
These are just a few observations I made while playing with DROID, you can choose whether to deal with these:

- Clicking on branch when first opening project should open the branch in a new tab. All clicks in DROID that make the user leave DROID should probably go to a new tab.
- Any way we can do auto-refresh every 5 sec while waiting for a build?
- A more clear progress bar for long-running processes would be good (IHCC file upload use case); In one instance (IHCC file upload use case), for the second half of the process did not yield any UI feedback (not even a mouse wheel)
- When using CMD + click on google docs link, the action open window also triggers (two tabs are being opened)

**Comment by jamesaoverton** [comment]
Good suggestions, thanks!

**Comment by jamesaoverton** [comment]
The UI has changed quite a bit, and now has different problems :smile:! So I'll close this.
