### ISSUE TITLE
During login, redirect to where you were

### ISSUE THREAD

**Issue by matentzn** [ontodev/droid#57]
Right now, logging-in (with GitHub) redirects you to the DROID root page. It would be great if you were simply redirected to the pages you were actually on during the redirect.

**Comment by lmcmicu** [comment]
This is specified using the `:landing-uri` parameter of Ring-OAuth2's `(wrap-oauth2` function. It looks like we can make this more flexible using the `:redirect-handler` parameter (see the README for: https://github.com/weavejester/ring-oauth2)
