### ISSUE TITLE
Status line on branch page should link to PR (if one exists)

### ISSUE THREAD

**Issue by matentzn** [ontodev/droid#59]
@jamesaoverton had another idea, but I forgot it again in the heat of the moment. Right now the PR opens in the DROID tab which is not desirable.

**Comment by matentzn** [comment]
There is this comment in my notes: `status bar should show PR if it exists`

**Comment by jamesaoverton** [comment]
DROID's project pages (e.g. https://droid.ontodev.com/IHCC) have a table like this:

Branch | Pull request | Git status
-- | -- | --

The "Pull request" column links to the PR for that branch, if there is one. This is good -- no changes needed.

DROID's branch pages (e.g. https://droid.ontodev.com/IHCC/branches/master) include the "Git status" part (e.g. "0 ahead, 0 behind origin/master"). They should also include the "Pull request" link (if there is a PR). The link to the GitHub branch (current) and the link to the PR (new) should both open in a new tab.
