### ISSUE TITLE
Allow use of Version Control action buttons in workflow

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/droid#61]
Add ability to reference version control actions (e.g., commit) in the workflow at the top of a `Makefile`.

Right now, you could do it by putting HTML in the workflow but it wouldn't look very nice in the Makefile 🙂 

Maybe if the "link" part is the same as an existing button, (e.g., `[Commit](Commit)`) that means use the button. The downside is you cannot have a make task named `Commit` (or `Status`, `Push`, etc...)

**Comment by matentzn** [comment]
Aw this would be so cool! Would it be possible to be able to refer to these through something like `[Commit](droid_Commit)` to remove the ambiguity? Not many people will use make goals like "push" and "pull", but I have seen "status" and definitely `diff`.

**Comment by jamesaoverton** [comment]
Becky and I were thinking that to get a DROID version control button you need to have exactly `[Status](Status)`. So the escape hatch if you want to use your own "status" task is just changing the case or link text, e.g. `[check status](status)` would run your `make status`.

Now I'm thinking it would be better for DROID to look for `git .*` in the HREF, so `[Commit](git commit)` would tell DROID to show the yellow Commit button.

Or maybe DROID just looks for strings like "Run `git commit`" (without the Markdown link). That would be a bigger change.

The overall design goal is that reading Workflow section of the Makefile in your text editor should still be clear, even if you've never heard of DROID.

**Comment by matentzn** [comment]
> Now I'm thinking it would be better for DROID to look for git .* in the HREF, so [Commit](git commit) would tell DROID to show the yellow Commit button.

I like this option very much! :)

**Comment by jamesaoverton** [comment]
I think the `[Commit](git commit)` option is best. The user can label the button what they want. DROID will look in the HREF for certain `git [action]` patterns and use the appropriate colour. I think this should only work for the git action DROID supports, not just any git action, but I could be convinced otherwise.

**Comment by matentzn** [comment]
I fully agree! Awesome!
