### ISSUE TITLE
Incorrect "Git status" on "Branches" page?

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/droid#63]
On the branch page for a project, I clicked refresh after not pulling updates for some time. I expected to see the "Git status" section change, but it still displayed:
> 0 ahead, 0 behind origin/master

I went into the branch and ran "Pull" and successfully pulled changes, so I would have expected the "Git status" to show some sort of change before that.

It also looks like merged PRs might disappear?
![image](https://user-images.githubusercontent.com/16750150/95471640-02d07800-0937-11eb-8a69-a8b8bb58eb29.png)

Both `droid-fixes` and `gizmos-tree` had PRs that have since been merged. Should they still show up or should there be another notice that lets you know if they've been merged into `master`? This feature might be a little complicated, though, just a question.

**Comment by jamesaoverton** [comment]
DROID doesn't automatically run `git fetch` or `git status`. That would be slow and maybe unexpected. So these are the values that DROID remembers from the last time `git status` was run on that branch.

I agree that it can be a bit confusing. We could add the date that it was last checked, or maybe be more clever about it somehow.

**Comment by jamesaoverton** [comment]
@lmcmicu Could we track the time that the status was checked, and display it somewhere? Maybe "Git status (50 minutes ago)" or "0 ahead, 0 behind origin/master (50 minutes ago)"?

**Comment by lmcmicu** [comment]
@jamesaoverton I'm not convinced this issue makes sense. The status is checked every time the page is refreshed. Here is the output of the log for a refresh of the project page:
```
2021-01-26 19:08:09.830-0500-DEBUG Processing request in render-project with params: {:project-name "for-testing-with-droid"}
2021-01-26 19:08:09.832-0500-DEBUG Running git status --short --branch --porcelain /home/mike/Knocean/droid/projects/for-testing-with-droid/workspace/master without a container
2021-01-26 19:08:09.864-0500-DEBUG Running git status --short --branch --porcelain /home/mike/Knocean/droid/projects/for-testing-with-droid/workspace/five without a container
2021-01-26 19:08:09.877-0500-DEBUG Running git status --short --branch --porcelain /home/mike/Knocean/droid/projects/for-testing-with-droid/workspace/one without a container
```

Similarly for the branch pages.

**Comment by lmcmicu** [comment]
Wait ... after looking more closely at the issue description I think I misunderstood. What the "X minutes" is supposed to refer to is the amount of time since the last `fetch` (or `pull`), correct? Ok, that makes a bit more sense ... will need to think about it.

**Comment by lmcmicu** [comment]
I think we can do this pretty simply by having the server call:

`stat -c %Y .git/FETCH_HEAD`

(or something similar).

**Comment by lmcmicu** [comment]
Note to self: See https://stackoverflow.com/a/9229377/8599709

**Comment by lmcmicu** [comment]
In answer to @beckyjackson's question about merged PRs: They are not shown. Only PRs that have the `state`: `open` are displayed. If this needs to be more explicit we can change the heading to "Open pull requests" instead of "pull requests".

Showing merged PRs is not straightforward, since GitHub doesn't make this information available through its API. See: https://docs.github.com/en/rest/reference/pulls

The possible statuses to filter on are `open`, `closed`, and `all`.

**Comment by jamesaoverton** [comment]
1. Yes, I'd like to display a time since last refresh. Checking the modification time for `.git/FETCH_HEAD` makes sense. It might be easier to do in Clojure/Java without shelling out.
2. I'd be happy just renaming the column header to "Open pull request".

**Comment by lmcmicu** [comment]
If it's alright with you I'd like to make (2) be: "Open PR" instead of "Open pull request". I'd prefer not to widen the column, especially now that we're adding an "(X minutes ago)" string to the status column.

**Comment by jamesaoverton** [comment]
Sure, makes sense.
