### ISSUE TITLE
Refresh remote branches automatically more often

### ISSUE THREAD

**Issue by lmcmicu** [ontodev/droid#73]
Currently the branch list is refreshed automatically only when it is empty (or manually when the Refresh button is pressed), but we are able to do this more often now that our request quota with GitHub Apps is larger.

**Comment by jamesaoverton** [comment]
See also #63

**Comment by lmcmicu** [comment]
I was the one who opened this issue originally because of some consistency problems in the branch list that needed manual Refreshes to resolve. After changes to DROID that I made some time ago, however, I don't think this issue that I added is needed anymore as the server now updates the remote branch list: (1) when it is empty and either the project page or a branch page is loaded, (2) before anything is pushed or pulled. It could still happen that the list becomes stale if others are working on remote branches outside of DROID, but even with that I'm not sure there's a need to refresh the list any more than we do now.

But I will defer to those who have been actually using DROID for real. Is the user experience alright as it stands, or do we need this?

**Comment by jamesaoverton** [comment]
Ok, let's close this in favour of #63.
