### ISSUE TITLE
Bug: DROID unable to actually kill running processes that are running in docker

### ISSUE THREAD

**Issue by lmcmicu** [ontodev/droid#86]
I'm surprised no one noticed this before, but while processes are successfully killed after pressing the Cancel (or Kill) button when DROID is running in non-docker mode, this doesn't work for processes running in docker. At least it doesn't work in my setup.

**Comment by matentzn** [comment]
Oh! Wow. I have actually never used ODK in Droid! only outside of it. Ctrl+C kills a running container on the terminal.. Good early spot of an issue that could be quite annoying later down the line!
