### ISSUE TITLE
Stop rendering Make actions as buttons

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/droid#91]
In the early days of the DROID design there was a clear distinction between Make tasks/actions and file views. Since then we've added directories but more importantly we've added CGI scripts. To my mind, a CGI script might be doing something "verby" like a Make task, but it also might just be serving a file. DROID has no way of knowing the difference.

We could add something to the Workflow that would distinguish button vs. link for CGI scripts. But I think it would be better to drop the distinction, and stop rendering Make tasks as buttons -- everything in the workflow will be rendered as a link.

I'm pretty sure that someone could just write HTML with buttons in the Workflow, if they really want buttons. It would be good to test this, and if it works add a note to the README about using HTML in Workflow blocks. (If it doesn't work, let's not bother to add this feature, right now.)

**Comment by lmcmicu** [comment]
After discussing this more with @jamesaoverton we decided that before implementing this issue, we need to think a bit more about how to handle action buttons and non-safe CGI scripts in the case where a user is logged out. 

Note that DROID currently does not distinguish between safe and unsafe scripts. It treats them all as unsafe. They are also clickable from the workflow, though when clicked they redirect to a "401 - Unauthorized" page.

As for action buttons, currently DROID removes the href from them and adds the `disabled` attribute to prevent the user from clicking them.

**Comment by jamesaoverton** [comment]
I changed my mind about this. Closing in favour of #100.
