### ISSUE TITLE
Add more documentation to the README

### ISSUE THREAD

**Issue by lmcmicu** [ontodev/droid#99]
We need documentation for:
- local-mode configuration
- github-app-mode configuration
- generating the DROID executable from source
- setting up DROID as a `systemd` service.

**Comment by cmungall** [comment]
I also recommend links to existing droid instances and repos that use droid. Examples are often the best documentation!

Screenshots are also awesome

**Comment by jamesaoverton** [comment]
Agreed. There is good progress on the README this big PR #82, which is just about ready to land:

https://github.com/ontodev/droid/blob/improvements/README.md

Yes, we can link to the main DROID instance here: https://droid.ontodev.com/

I also plan to write a "What DROID is good for" / "What you can do with DROID" doc, after #82 lands.

The trick is to stop asking @lmcmicu for changes :smile:
